# Generated by Django 3.0.8 on 2020-08-10 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0006_auto_20200810_1059'),
        ('producto', '0002_auto_20200809_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(db_column='razonsocial', on_delete=django.db.models.deletion.CASCADE, to='proveedor.Proveedor'),
        ),
    ]
