# Generated by Django 3.0.8 on 2020-08-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonsocial', models.CharField(max_length=300)),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=300)),
                ('representante', models.CharField(max_length=300)),
                ('fechacontratacion', models.CharField(max_length=300)),
            ],
        ),
    ]
