# Generated by Django 3.0.8 on 2020-08-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.CharField(default='a@b.com', max_length=300),
            preserve_default=False,
        ),
    ]
