# Generated by Django 3.0.8 on 2020-07-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='static/images/')),
                ('descripcion', models.TextField()),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
