# Generated by Django 3.0.8 on 2020-08-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200806_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticky',
            name='color',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
