# Generated by Django 3.0.8 on 2020-08-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_sticky_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sticky',
            old_name='encabezado',
            new_name='subtitulo',
        ),
        migrations.RenameField(
            model_name='sticky',
            old_name='piedepagina',
            new_name='titulo',
        ),
    ]
