# Generated by Django 3.0.8 on 2020-08-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200806_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimoniañ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('color', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='static/images/')),
            ],
        ),
    ]
