# Generated by Django 3.0.8 on 2020-08-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_testimoniañ'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimoniañ',
            new_name='Testimonia',
        ),
    ]
