# Generated by Django 3.0.8 on 2020-08-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200806_0829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonia',
            new_name='Testimonial',
        ),
    ]
