# Generated by Django 3.0.8 on 2020-08-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_testimonial_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticky',
            name='color',
            field=models.CharField(max_length=300),
        ),
    ]
