# Generated by Django 3.0.8 on 2020-07-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medicinas',
            new_name='Productos',
        ),
    ]
