# Generated by Django 3.0.8 on 2020-08-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productos_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
